### ISSUE TITLE
An error :(

### ISSUE THREAD

**Issue by pjotreek** [Terra-rian/snakecord#10]
Hello Terra-rian! I used your node package module in my bot (discord.js v12). I used it for some time then i found a bug... 
When snek embed message gets deleted by server admin bot instantly crashes.. Here is error: 

C:\Users\piotr\Desktop\Hexagon\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Unknown Message
    at RequestHandler.execute (C:\Users\piotr\Desktop\Hexagon\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\piotr\Desktop\Hexagon\node_modules\discord.js\src\rest\RequestHandler.js:39:14) {
  method: 'patch',
  path: '/channels/870728153461575730/messages/881200565982490654',
  code: 10008,
  httpStatus: 404
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Terra-rian** [comment]
Hey there! What you're describing isn't a bug, but just the way Discord works.

When a message gets deleted, you can no longer execute actions on the message, such as editing an embed (which is what this module does).

To prevent this, simply don't delete the message generated by the bot. That way, actions such as editing can still be performed, with no errors.
