### ISSUE TITLE
Stolen Code

### ISSUE THREAD

**Issue by TheTurkeyDev** [Terra-rian/snakecord#11]
Hello, I wanted to avoid making this ticket and prefer to contact you another way, but I can't find any other contact information. I have recently been informed that this code exists and after looking it over I have found that It is a direct copy of the snake code from my project (https://github.com/TheTurkeyDev/Discord-Games/commit/1155479038313547e70258da5389b20d01cf0b9e). I see that no attribution has been given to me in any capacity as well. I see that you are not the original developer of this, so I understand that you may not be aware of this at all. I would like to chat with you and discus how this can all be resolved. If Discord works best for you, feel free to add me there (TurkeyDev#6719), or let me know what other way to communicate would be best.

**Comment by Terra-rian** [comment]
Hey there, thanks for reaching out. I've looked at your repo, and yes, it does look like the code was taken from there. You are correct, I am not the original author (I have only taken the maintainer position for a previously defunct package).

I'll be happy to add you as the original author on the README in the next version, and if that doesn't suit you, I can add you on Discord so we can discuss it further.

**Comment by TheTurkeyDev** [comment]
Yeah definitely hit me up on Discord just so we can chat further. Definitely don't want to stop you from maintaining this, especially with the rewrites I see you making.

**Comment by Bunny-B-Ruder** [comment]
Can someone tell me why does it respond to reactions other than than the player who started it

**Comment by TheTurkeyDev** [comment]
This was resolved in DM's. All is good now. Look forward to seeing the work that @Terra-rian does!

@Bunny-B-Ruder I wrote the code to only allow the user who started it to be able to play the game so that people wouldn't mess with others game's and ruin them.
