### ISSUE TITLE
Error when edit

### ISSUE THREAD

**Issue by Zaikonurami** [Terra-rian/snakecord#6]
Hello, I have a problem, all works but when I go to play the console throws this error:

```
(node:583) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/home/runner/KitsunityApp/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/KitsunityApp/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
(node:583) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 0)
```

And this is my code, using a command handler

```js
const SnakeGame = require('snakecord');
const snakeGame = new SnakeGame({
    title: 'Serpiente 🐍',
    color: "RANDOM",
    timestamp: true,
    gameOverTitle: "Juego terminado u.u"
});

module.exports = {
  name: 'snake',
  description: "Juega al clasico serpiente",
  aliases: ['snakegame'],
  usage: '',
  cooldown: 2,
  args: 0,
  catergory: 'Entretenimiento',
  async execute(client, message, args) {
    message.channel.send('Cargando...')
    return snakeGame.newGame(message);
  }
};
```
Please solve this, I really want to use this library

**Comment by Terra-rian** [comment]
Hey there, thanks for bringing this to my attention. I'd need to know a few things before I can help you resolve this:
- Your Node.js version
- Your Discord.js version
- Any other details, such as operating systems and where you host the bot, if applicable
- Did you make any modifications to the module code?

Thank you.

**Comment by Prince527GitHub** [comment]
This happens to me to but I don't even get the message!

**Comment by Terra-rian** [comment]
@Prince527GitHub can you open a separate issue please? Make sure to include all relevant info, including the error message(s) you get, your Node.js version, and your Discord.js version, if you use that.

**Comment by Zaikonurami** [comment]
Hello again, here are my details:

* Discord.js: Lastest (12.5.3)
* Node.js: 12.16.1
* Host: repl.it
* I only modify that file, because its a command handler

Thanks for help me to solve this

**Comment by Terra-rian** [comment]
Ok, nothing seems out of the ordinary, I'd recommend you don't use repl.it as a host, but that's up to you. Does the error occur when the initial embed is sent? Or when you actually press on the reactions, and the snake tries to move?

**Comment by KitsuneCode** [comment]
I resolved the issue, thanks for your help, the problem was caused because the library `discord-buttons` cuases conflicts with the reaction functions

**Comment by Zaikonurami** [comment]
I resolved the issue, thanks for your help, the problem was caused because the library `discord-buttons` causes conflicts with the reaction functions
