### ISSUE TITLE
Discord.js v13 incompatibility: Cannot send an empty message

### ISSUE THREAD

**Issue by DreamBoy65** [Terra-rian/snakecord#7]

**Comment by Terra-rian** [comment]
Can you show me the stack trace? And, can you tell me your system specifications? (Discord.js version, host, etc).

**Comment by DreamBoy65** [comment]
I'm on latest v- od discord.js

I think bcz discord changed to edit embed by "message.channel.send({embed})

**Comment by Terra-rian** [comment]
Yeah, this package doesn't support the development/master branch of Discord.js (`discord.js@dev`) yet. I'm waiting on the actual stable release to update this package to support v13 (as things are still very unstable and can break at any moment). You'll have to downgrade the version of Discord.js or remove this package in the meantime.

**Comment by DreamBoy65** [comment]
Ok, thank you.
